[package]
name = "gct-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = "1"
serde_derive = "1"
plotters = "0.3.1"
chrono = "0.4.19"