version: '3'

x-environment: &environment
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: postgres
  PGSSLMODE: disable
  TZ: "Asia/Tokyo"

services:
  rust:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - rust-target:/workspace/app/target
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment: *environment
      
  postgres:
    image: postgres:latest
    platform: linux/x86_64
    restart: always
    environment: *environment
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  rust-target:
  postgres: